import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/home.module.scss'
import Panel from './components/panel/panel'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Point App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <section>
          <Panel />
        </section>
        <section className={styles.feed}>
            <p>hola</p>
        </section>
        
      </main>

      
    </div>
  )
}
